<!-- remove in override for allconnect -->
<!-- <?php if ($otherProvidersNeeded == 'true'): ?>
          <div id="multipleProvidersAlert">
          <div class="close-alert"></div>
          <strong>Hmmm, looks like <span><?php echo $providerName ?></span> is not available at your address.</strong>
          <p>Good news! Multiple partners in your area are offering great services and plans.</p>
          <div class="bg-border"></div>
          <div class="bg-cover"></div>
        </div>
<?php endif; ?> -->

<aside class="alerts otherETProducts">
	<div class="container">
		<div class="alert alert-info alert-dismissible center-block" role="alert">
		  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		  <strong></strong>
		</div>
	</div>
</aside>

<!-- <aside class="alerts" id="alert-no-products" ng-if="noProductsToShow==true">
  <div class="container">
    <div class="alert alert-info alert-dismissible center-block" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <strong>No products test - We couldn't find any plans in this category for your address</strong>
    </div>
  </div>
</aside> -->